#!/bin/bash

# 公司的 WiFi 自动就可以翻墙，但是家里的 WiFi 就得自己设置；
# 这个脚本根据 WiFi 的 SSID 判断是否要设置翻墙代理（auto proxy）

COMPANY_WIFI="eleme"  					# 公司的 WiFi 名包含的字段
NS="Wi-Fi"								# 网络类型
URL="http://location/of/your/proxy/url" # 翻墙代理的地址

toggleVPN(){
	if [[ "$1" == "off" ]]
		then
			networksetup -setautoproxyurl $NS " "
			networksetup -setautoproxystate $NS off
			echo "关闭 VPN 成功"
		else
			networksetup -setautoproxyurl $NS $URL
			networksetup -setautoproxystate $NS on
			echo "开启 VPN 成功"
		fi
}
# WIFI_INFO 是一个包含 WiFi SSID 的字符串（也包含其他内容）
WIFI_INFO=`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I`
if [[ "$WIFI_INFO" == *"$COMPANY_WIFI"* ]]
then
	toggleVPN off
else
	toggleVPN on
fi

